version: "3.8"
services:
  # image micro-gateway
  micro_gateway:
    build:
      args:
        - user=fhariano
        - uid=1000
      context: ./
      dockerfile: dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - microgateway

  # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8098:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - microgateway

networks:
  microgateway:
    driver: bridge
